export const projectsArray = [
  {
    name: 'E-Commerce',
    tools: 'ReactJS - ExpressJS - MongoDB',
    img: './assets/shop.png',
    github: 'https://github.com/datodat/e-commerce',
    live: 'https://datos-shop.herokuapp.com/',
  },
  {
    name: 'Posts',
    tools: 'ReactJS - ExpressJS - MongoDB',
    img: './assets/posts.png',
    github: 'https://github.com/datodat/posts',
    live: 'https://datos-posts.herokuapp.com/',
  },
  {
    name: 'Countries',
    tools: 'ReactJS',
    img: './assets/countries.png',
    github: 'https://github.com/datodat/Countries-app',
    live: 'https://countries-app-lac.vercel.app/',
  },
  {
    name: 'GitHub Users',
    tools: 'ReactJS',
    img: './assets/github.png',
    github: 'https://github.com/datodat/github-users',
    live: 'https://github-users-smoky.vercel.app/',
  },
  {
    name: 'Music Player',
    tools: 'ReactJS',
    img: './assets/musicPlayer.png',
    github: 'https://github.com/datodat/music_player',
    live: 'https://music-player-pink-five.vercel.app/',
  },
  {
    name: 'Rating App',
    tools: 'ReactJS',
    img: './assets/rating.png',
    github: 'https://github.com/datodat/interactive_rating',
    live: 'https://rating-app-wheat.vercel.app/',
  },
  {
    name: 'Todo List',
    tools: 'ReactJS',
    img: './assets/todolist.png',
    github: 'https://github.com/datodat/Todo-List',
    live: 'https://todo-list-rust-one.vercel.app/completed',
  },
  {
    name: 'Random Quotes',
    tools: 'ReactJS',
    img: './assets/quotes.png',
    github: 'https://github.com/datodat/Random-Quotes',
    live: 'https://random-quotes-gamma.vercel.app/',
  },
  {
    name: 'Redberry Test app',
    tools: 'ReactJS',
    img: './assets/redberry.png',
    github: 'https://github.com/datodat/redberry',
    live: 'https://redberry-theta.vercel.app/',
  },
  {
    name: 'Weather app',
    tools: 'ReactJS',
    img: './assets/weather.png',
    github: 'https://github.com/datodat/weather',
    live: 'https://weather-psi-bice.vercel.app/',
  },
  {
    name: 'Wikipedia search',
    tools: 'ReactJS',
    img: './assets/wikisearch.png',
    github: 'https://github.com/datodat/Wikipedia-search',
    live: 'https://wikipedia-search-two.vercel.app/',
  },
  {
    name: 'Tic Tac Toe',
    tools: 'ReactJS',
    img: './assets/ticTacToe.png',
    github: 'https://github.com/datodat/Tic-Tac-Toe',
    live: 'https://tic-tac-toe-zeta-six.vercel.app/',
  },
  {
    name: 'Sign-up form',
    tools: 'HTML/CSS - JS',
    img: './assets/signUpForm.png',
    github: 'https://github.com/datodat/sign-up-form',
    live: 'https://sign-up-form-puce.vercel.app/',
  },
]